language: ruby
cache: bundler
deploy:
  provider: heroku
  skip-cleanup: true
  app: maintainance-window-tasks
  api_key:
    secure: ixrUeN5tygAg9H1A3ZYvnDvWFvlnBcehiaP+UNKIhaPyeBnky8pOHcAHRDocrubHEr2YsAhetJqpBBWAjw8KdRsErrTR68zXJGbA0EbIwbZtwBStkV5MjoHnfQFVLnNV+MzUjAKyyNyV7ZQvNGvGLQmoIpLzlqFiT06HKfg5iHzq+AryHhaGjaqos1y5sqpz7aC3cJWHoOfzxyjExAjLppVa9q62hYJfisXhnIdIOEXW3g5gLYFNbIRlgkYLT5uSSbGyrPsVAzjtIe4s9Dvod8RP4WlSWGLCxqAFLgkm9uz2pIh7pcGlZ92IvvLPh7AWd+0edfHJCRRQfp/UjXn41jGsOEQgIakU6x/zptbrK+AazlfG706HCI1JadX7nWeNr0hBs19sCi73sjm9+pAKrCtd3XToBik6w1V1nMpKm62UXyHJdov+53IdV2AIbYhTIfgKur8oPJUz0J5AL5ty7bfJR9lf8aRCBxSpXA7hiq0krxOxmDBPVZRofoGOBGNeYKnwzr4XzwDMcxrLJ5Zo10HUH6q1puL4zbAbgAJ1jSP7f+5lW2JGkhvl6WQw1Iyp1VPxgvz53opuhihPgp6LdZVVOpcul7Q9wXO5VrZEOJhfGAy47RCIKFvcenYBHP4PlDTMDyU/qV5Q081Qa1labREGtStnQeLOxTT+BwjGywg=
